### ISSUE TITLE
Tidal stripping?

### ISSUE THREAD

**Issue by wally800** [Nbodypp/HOW_final#12]
Without adaptive timestepping, does anyone know if our code is currently capable of demonstrating tidal stripping of, say, a binary star system coming close to a blackhole?  I think that would be cool to show during our presentation.

**Comment by smoh** [comment]
I've been working on something similar

**Comment by wally800** [comment]
Cool.

**Comment by smoh** [comment]
I'm not sure if I can do this.. would you like to try?

**Comment by wally800** [comment]
Do you have anything you've tried so far?

**Comment by wally800** [comment]
Success!  I will be pushing shortly.

**Comment by wally800** [comment]
For the tidal stripping example the orbits change significantly as I change the timestep, leading me to believe that we should use a better integrator than the leapfrog integrator and/or need to incorporate adaptive timestepping.  Feel free to try Runge-Kutta.
