### ISSUE TITLE
testEuler_SI no longer compiling

### ISSUE THREAD

**Issue by wally800** [Nbodypp/HOW_final#13]
`make testEuler_SI` is no longer working and I haven't been able to figure out why.  There's a long list of (to me) not helpful problems that get printed out:

ast1403-astro:src joshuajw$ make testEuler_SI
c++ -Wall -O3 -std=c++0x -Ivendor -Ivendor/simpleini -I.  -o ./tests/testEuler_SI particle.o force_direct.o euler_semi_implicit.o tests/testEuler_SI.o
Undefined symbols for architecture x86_64:
  "_G", referenced from:
      Force::update_acceleration(std::__1::vector<Particle, std::__1::allocator<Particle> >&) const in force_direct.o
      ____C_A_T_C_H____T_E_S_T____9() in testEuler_SI.o
  "Catch::ResultBuilder::endExpression()", referenced from:
      ____C_A_T_C_H____T_E_S_T____9() in testEuler_SI.o
  "Catch::ResultBuilder::setResultType(bool)", referenced from:
      Catch::ResultBuilder& Catch::ExpressionLhs<int const&>::captureExpression<(Catch::Internal::Operator)0, int>(int const&) in testEuler_SI.o
      Catch::ResultBuilder& Catch::ExpressionLhs<Integrator* const&>::captureExpression<(Catch::Internal::Operator)0, long>(long const&) in testEuler_SI.o
      Catch::ResultBuilder& Catch::ExpressionLhs<double const&>::captureExpression<(Catch::Internal::Operator)0, double>(double const&) in testEuler_SI.o
  "Catch::ResultBuilder::useActiveException(Catch::ResultDisposition::Flags)", referenced from:
      ____C_A_T_C_H____T_E_S_T____9() in testEuler_SI.o
  "Catch::ResultBuilder::react()", referenced from:
      ____C_A_T_C_H____T_E_S_T____9() in testEuler_SI.o
  "Catch::ResultBuilder::setOp(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      Catch::ResultBuilder& Catch::ExpressionLhs<int const&>::captureExpression<(Catch::Internal::Operator)0, int>(int const&) in testEuler_SI.o
      Catch::ResultBuilder& Catch::ExpressionLhs<Integrator* const&>::captureExpression<(Catch::Internal::Operator)0, long>(long const&) in testEuler_SI.o
      Catch::ResultBuilder& Catch::ExpressionLhs<double const&>::captureExpression<(Catch::Internal::Operator)0, double>(double const&) in testEuler_SI.o
  "Catch::ResultBuilder::setLhs(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      Catch::ResultBuilder& Catch::ExpressionLhs<int const&>::captureExpression<(Catch::Internal::Operator)0, int>(int const&) in testEuler_SI.o
      Catch::ResultBuilder& Catch::ExpressionLhs<Integrator* const&>::captureExpression<(Catch::Internal::Operator)0, long>(long const&) in testEuler_SI.o
      Catch::ResultBuilder& Catch::ExpressionLhs<double const&>::captureExpression<(Catch::Internal::Operator)0, double>(double const&) in testEuler_SI.o
  "Catch::ResultBuilder::setRhs(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      Catch::ResultBuilder& Catch::ExpressionLhs<int const&>::captureExpression<(Catch::Internal::Operator)0, int>(int const&) in testEuler_SI.o
      Catch::ResultBuilder& Catch::ExpressionLhs<Integrator* const&>::captureExpression<(Catch::Internal::Operator)0, long>(long const&) in testEuler_SI.o
      Catch::ResultBuilder& Catch::ExpressionLhs<double const&>::captureExpression<(Catch::Internal::Operator)0, double>(double const&) in testEuler_SI.o
  "Catch::ResultBuilder::ResultBuilder(char const*, Catch::SourceLineInfo const&, char const*, Catch::ResultDisposition::Flags)", referenced from:
      ____C_A_T_C_H____T_E_S_T____9() in testEuler_SI.o
  "Catch::SourceLineInfo::SourceLineInfo(char const*, unsigned long)", referenced from:
      ____C_A_T_C_H____T_E_S_T____9() in testEuler_SI.o
      __GLOBAL__I_a in testEuler_SI.o
  "Catch::Detail::rawMemoryToString(void const*, unsigned long)", referenced from:
      Catch::ResultBuilder& Catch::ExpressionLhs<Integrator* const&>::captureExpression<(Catch::Internal::Operator)0, long>(long const&) in testEuler_SI.o
  "Catch::AutoReg::AutoReg(void (*)(), Catch::SourceLineInfo const&, Catch::NameAndDesc const&)", referenced from:
      __GLOBAL__I_a in testEuler_SI.o
  "Catch::AutoReg::~AutoReg()", referenced from:
      __GLOBAL__I_a in testEuler_SI.o
  "Catch::toString(double)", referenced from:
      Catch::ResultBuilder& Catch::ExpressionLhs<double const&>::captureExpression<(Catch::Internal::Operator)0, double>(double const&) in testEuler_SI.o
  "Catch::toString(int)", referenced from:
      Catch::ResultBuilder& Catch::ExpressionLhs<int const&>::captureExpression<(Catch::Internal::Operator)0, int>(int const&) in testEuler_SI.o
  "Catch::ResultBuilder::shouldDebugBreak() const", referenced from:
      ____C_A_T_C_H____T_E_S_T____9() in testEuler_SI.o
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [testEuler_SI] Error 1

**Comment by smoh** [comment]
should be fixed with a85e136f660f4547a0e6f0ef7d7feb4fb7290488
