### ISSUE TITLE
additional forces are added Nparticle times

### ISSUE THREAD

**Issue by smoh** [Nbodypp/HOW_final#14]
Additional force calculation is _inside_ the loop of gravity calculation for each particle, adding them Nparticle times. I think this persisted from the beginning 3ec3e0d5, but was never caught because the test written was with only one particle.

**Comment by smoh** [comment]
fixed in b8d74cfa588f4e045d1003cbc13df54799d970e1

**Comment by wally800** [comment]
Is this likely why my Earth-Moon in a Sun-like central potential example
was failing?  Sounds about right.

**Comment by smoh** [comment]
yes, I think this must be it. Good thing we caught it.
